import React, {useState,useRef,useEffect} from 'react'
import axios from "axios";

export function maxpos(genmap,setcouponlist){
//function pos1(params) {}

axios.post("http://localhost:5000/coupon/add",genmap[1])
axios.post("http://localhost:5000/coupon/add",genmap[2])
axios.post("http://localhost:5000/coupon/add",genmap[3])
axios.post("http://localhost:5000/coupon/add",genmap[4])
axios.post("http://localhost:5000/coupon/add",genmap[5])
axios.post("http://localhost:5000/coupon/add",genmap[6])
axios.post("http://localhost:5000/coupon/add",genmap[7])
axios.post("http://localhost:5000/coupon/add",genmap[8])
axios.post("http://localhost:5000/coupon/add",genmap[9])
axios.post("http://localhost:5000/coupon/add",genmap[10])
axios.post("http://localhost:5000/coupon/add",genmap[11])
axios.post("http://localhost:5000/coupon/add",genmap[12])
axios.post("http://localhost:5000/coupon/add",genmap[13])
axios.post("http://localhost:5000/coupon/add",genmap[14])
axios.post("http://localhost:5000/coupon/add",genmap[15])
axios.post("http://localhost:5000/coupon/add",genmap[16])
axios.post("http://localhost:5000/coupon/add",genmap[17])
axios.post("http://localhost:5000/coupon/add",genmap[18])
axios.post("http://localhost:5000/coupon/add",genmap[19])
axios.post("http://localhost:5000/coupon/add",genmap[20])
axios.post("http://localhost:5000/coupon/add",genmap[21])
axios.post("http://localhost:5000/coupon/add",genmap[22])
axios.post("http://localhost:5000/coupon/add",genmap[23])
axios.post("http://localhost:5000/coupon/add",genmap[24])
axios.post("http://localhost:5000/coupon/add",genmap[25])
axios.post("http://localhost:5000/coupon/add",genmap[26])
axios.post("http://localhost:5000/coupon/add",genmap[27])
axios.post("http://localhost:5000/coupon/add",genmap[28])
axios.post("http://localhost:5000/coupon/add",genmap[29])
axios.post("http://localhost:5000/coupon/add",genmap[30])
axios.post("http://localhost:5000/coupon/add",genmap[31])
axios.post("http://localhost:5000/coupon/add",genmap[32])
axios.post("http://localhost:5000/coupon/add",genmap[33])
axios.post("http://localhost:5000/coupon/add",genmap[34])
axios.post("http://localhost:5000/coupon/add",genmap[35])
axios.post("http://localhost:5000/coupon/add",genmap[36])
axios.post("http://localhost:5000/coupon/add",genmap[37])
axios.post("http://localhost:5000/coupon/add",genmap[38])
axios.post("http://localhost:5000/coupon/add",genmap[39])
axios.post("http://localhost:5000/coupon/add",genmap[40])
axios.post("http://localhost:5000/coupon/add",genmap[41])
axios.post("http://localhost:5000/coupon/add",genmap[42])
axios.post("http://localhost:5000/coupon/add",genmap[43])
axios.post("http://localhost:5000/coupon/add",genmap[44])
axios.post("http://localhost:5000/coupon/add",genmap[45])
axios.post("http://localhost:5000/coupon/add",genmap[46])
axios.post("http://localhost:5000/coupon/add",genmap[47])
axios.post("http://localhost:5000/coupon/add",genmap[48])
axios.post("http://localhost:5000/coupon/add",genmap[49])
axios.post("http://localhost:5000/coupon/add",genmap[50])
axios.post("http://localhost:5000/coupon/add",genmap[51])
axios.post("http://localhost:5000/coupon/add",genmap[52])
axios.post("http://localhost:5000/coupon/add",genmap[53])
axios.post("http://localhost:5000/coupon/add",genmap[54])
axios.post("http://localhost:5000/coupon/add",genmap[55])
axios.post("http://localhost:5000/coupon/add",genmap[56])
axios.post("http://localhost:5000/coupon/add",genmap[57])
axios.post("http://localhost:5000/coupon/add",genmap[58])
axios.post("http://localhost:5000/coupon/add",genmap[59])
axios.post("http://localhost:5000/coupon/add",genmap[60])
axios.post("http://localhost:5000/coupon/add",genmap[61])
axios.post("http://localhost:5000/coupon/add",genmap[62])
axios.post("http://localhost:5000/coupon/add",genmap[63])
axios.post("http://localhost:5000/coupon/add",genmap[64])
axios.post("http://localhost:5000/coupon/add",genmap[65])
axios.post("http://localhost:5000/coupon/add",genmap[66])
axios.post("http://localhost:5000/coupon/add",genmap[67])
axios.post("http://localhost:5000/coupon/add",genmap[68])
axios.post("http://localhost:5000/coupon/add",genmap[69])
axios.post("http://localhost:5000/coupon/add",genmap[70])
axios.post("http://localhost:5000/coupon/add",genmap[71])
axios.post("http://localhost:5000/coupon/add",genmap[72])
axios.post("http://localhost:5000/coupon/add",genmap[73])
axios.post("http://localhost:5000/coupon/add",genmap[74])
axios.post("http://localhost:5000/coupon/add",genmap[75])
axios.post("http://localhost:5000/coupon/add",genmap[76])
axios.post("http://localhost:5000/coupon/add",genmap[77])
axios.post("http://localhost:5000/coupon/add",genmap[78])
axios.post("http://localhost:5000/coupon/add",genmap[79])
axios.post("http://localhost:5000/coupon/add",genmap[80])
axios.post("http://localhost:5000/coupon/add",genmap[81])
axios.post("http://localhost:5000/coupon/add",genmap[82])
axios.post("http://localhost:5000/coupon/add",genmap[83])
axios.post("http://localhost:5000/coupon/add",genmap[84])
axios.post("http://localhost:5000/coupon/add",genmap[85])
axios.post("http://localhost:5000/coupon/add",genmap[86])
axios.post("http://localhost:5000/coupon/add",genmap[87])
axios.post("http://localhost:5000/coupon/add",genmap[88])
axios.post("http://localhost:5000/coupon/add",genmap[89])
axios.post("http://localhost:5000/coupon/add",genmap[90])
axios.post("http://localhost:5000/coupon/add",genmap[91])
axios.post("http://localhost:5000/coupon/add",genmap[92])
axios.post("http://localhost:5000/coupon/add",genmap[93])
axios.post("http://localhost:5000/coupon/add",genmap[94])
axios.post("http://localhost:5000/coupon/add",genmap[95])
axios.post("http://localhost:5000/coupon/add",genmap[96])
axios.post("http://localhost:5000/coupon/add",genmap[97])
axios.post("http://localhost:5000/coupon/add",genmap[98])
axios.post("http://localhost:5000/coupon/add",genmap[99])
axios.post("http://localhost:5000/coupon/add",genmap[100])
.then(function (res){ setcouponlist(genmap)})
.catch(function (error) { alert(error); });


function expos(params) {
 
  axios.post("http://localhost:5000/coupon/add",JSON.stringify(genmap[1]))
  .then(function (res){ alert(JSON.stringify(res.data))})
  .catch(function (error) { alert(error); });
  
}
  }

export default function Push({genmap,setgenmap,maxpos}) {



  return (
    <div id="mmmm" hidden="hidden" ></div>
  )

}
